spring.application.name: circleci

spring.profiles.active: local

# kalendar api - opsi 1
calendar.url.kalenderindonesia: https://kalenderindonesia.com/api
calendar.codeapi.kalenderindonesia: APIGnkzE3esNM

# kalendar api - opsi 2
calendar.url.vercel: https://api-harilibur.vercel.app/api


# office365
incomingwebhook.url : https://bcaoffice365.webhook.office.com/webhookb2
incomingwebhook.group.explorer : 09a2a87a-c42a-43a7-a67f-39e9e02b0670@59daf140-4aee-4b77-80f4-4ea8bec86c2e/IncomingWebhook/9feadc214b6c4958859a1962f0f8605f/60f381ba-197c-43a6-a2a2-259f67ae0a8e
incomingwebhook.group.dailyupdate : 09a2a87a-c42a-43a7-a67f-39e9e02b0670@59daf140-4aee-4b77-80f4-4ea8bec86c2e/IncomingWebhook/5bfa4aca69994f45be965bfdbd13aad2/60f381ba-197c-43a6-a2a2-259f67ae0a8e

# github
github.raw.url: https://raw.githubusercontent.com
github.katabijak: casper4738/circleci-script/master/notes/kata-bijak-developer.json
