
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
 docker-save:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: docker-pull-image
          command: |
              docker pull mongo:3.4.23
              #docker pull jboss/keycloak:14.0.0
              #docker pull jboss/keycloak:14.0.0
              #docker pull quay.io/microcks/microcks-postman-runtime:latest
              #docker pull quay.io/microcks/microcks:latest

              docker images

workflows:
  workflow:
    jobs:
      - docker-save