
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - run:
          name: "test"
          command: |
              current_date=`date '+%d-%m-%Y'`
              echo "current_date ${current_date}"
              java -version
              ls -a
              chmod +x gradlew
              ./gradlew build
              java -jar build/libs/circleci.jar


workflows:
  workflow:
    jobs:
      - test