
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
 hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: hello
          command: |
              echo "HI ~Fandy~"

workflows:
  workflow:
    jobs:
      - hello