
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
 daily:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - run:
          name: build
          command: |
              java -version
              chmod +x gradlew
              ./gradlew build
      - run:
          name: execute
          command: |
              java -jar build/libs/circleci.jar --dailyupdate=true


workflows:
  workflow:
    triggers:
      - schedule:
          # https://www.worldtimebuddy.com/est-to-utc-converter
          # Run every day at 01 AM GMT+7
          # in  UTC is 6 PM
          cron: "00 01 * * 1-5"
          filters:
            branches:
              only:
                - daily-update

    jobs:
      - daily