
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
 daily:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - run:
          name: build
          command: |
              java -version
              chmod +x gradlew
              ./gradlew build
      - run:
          name: test
          command: |
              java -jar build/libs/circleci.jar --dailyupdate=true


workflows:
  workflow:
    jobs:
      - daily